const actionTypes = {
    SET_USER_INFO: 'SET_USER_INFO',
    LOAD_FOLLOWED_BY: 'LOAD_FOLLOWED_BY',
    LOAD_FOLLOWS: 'LOAD_FOLLOWS',
    
    LOAD_USER_VK: 'LOAD_USER_VK',
    LOAD_FRIENDS_VK: 'LOAD_FRIENDS_VK',
    LOAD_FRIENDS: 'LOAD_FRIENDS',
    LOAD_USER_LIKED_BY: 'LOAD_USER_LIKED_BY'
};

export { actionTypes }